name: Project Testing

on:
  push:
    branches: [ main ]

jobs:
  project_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.203'

      - name: Build Project
        run: dotnet build