name: Project Testing

on:
  push:
    branches: [ main ]

jobs:
  project_test:
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password!123
        ports:
          - 1433:1433
        options: >-
          --health-cmd "exit 0"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.203'

      - name: Build Project
        run: dotnet build
      
      - name: Run Tests
        run: dotnet test